# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
            args: [--maxkb=4096]

    - repo: local
      hooks:
          - id: prettier
            name: Run prettier
            entry: npx prettier --write
            language: system
            files: "\\.(js|ts|json|css|html|ya?ml|md)$"

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.0
      hooks:
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix]
          - id: ruff-format
            types_or: [python, pyi, jupyter]

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
