liveness:
    file:
        display: data/liveness/display

panel:
    device:
        width: 2200
        height: 1650
    update:
        interval: 120

influxdb:
    url: http://proxy.green-rabbit.net:8086
    org: home
    token: strBCB9segqccgxsR5Xe_9RnCqkBFYX9aOKvxVR4lr3iLEb7HXuGqsN40YU6DIb6TZm9bvKLW5OWQS7sB8AQbQ==
    bucket: sensor

# wall:
#   image:
#     - path: img/mascot.png
#       brightness: 2
#       offset_x: 1550
#       offset_y: 565

time:
    panel:
        width: 400
        height: 150
        offset_x: 1995
        offset_y: 740
        scale: 0.5

weather:
    panel:
        width: 2200
        height: 2000
        offset_x: 0
        offset_y: 0
        scale: 0.84
    data:
        yahoo:
            url: https://weather.yahoo.co.jp/weather/jp/13/4410/13113.html

    icon:
        sunset:
            path: img/sunset.png
            scale: 0.25
        sun:
            path: img/sun.png
            scale: 0.5
            brightness: 1.5
        arrow:
            path: img/arrow.png
            scale: 0.7
        thermo:
            path: img/thermo.png
            brightness: 1.2
            scale: 0.7
        clothes:
            path: img/clothes.png
            brightness: 1.2
            scale: 0.7
        clothing-full-1:
            path: img/cloching_icon_1_full.png
            scale: 0.5
            brightness: 2
        clothing-full-2:
            path: img/cloching_icon_2_full.png
            scale: 0.5
            brightness: 2
        clothing-full-3:
            path: img/cloching_icon_3_full.png
            scale: 0.45
            brightness: 2
        clothing-full-4:
            path: img/cloching_icon_4_full.png
            scale: 0.45
            brightness: 2
        clothing-full-5:
            path: img/cloching_icon_5_full.png
            scale: 0.5
            brightness: 2
        clothing-half-1:
            path: img/cloching_icon_1_half.png
            scale: 0.5
            brightness: 2
        clothing-half-2:
            path: img/cloching_icon_2_half.png
            scale: 0.5
            brightness: 2
        clothing-half-3:
            path: img/cloching_icon_3_half.png
            scale: 0.45
            brightness: 2
        clothing-half-4:
            path: img/cloching_icon_4_half.png
            scale: 0.45
            brightness: 2
        clothing-half-5:
            path: img/cloching_icon_5_half.png
            scale: 0.5
            brightness: 2
        precip:
            path: img/precip.png
            brightness: 1.3
            scale: 0.7
        wind:
            path: img/wind.png
            brightness: 1.3
            scale: 0.7

power:
    panel:
        width: 1600
        height: 510
        overlap: 380
    data:
        host:
            name: rasp-meter-5
            type: sensor.rasp
        param:
            name: power
            format: '{:,.0f}'
            unit: W
            range:
                - 0
                - 5000

rain_cloud:
    panel:
        offset_x: 1340
        offset_y: 0
        width: 860
        height: 1650
    legend:
        bar_size: 50
        offset_x: 370
        offset_y: 1610
        gamma: 0.5
    data:
        jma:
            url: https://www.jma.go.jp/bosai/nowc/#zoom:12/lat:35.682677/lon:139.762230/colordepth:deep/elements:hrpns&slmcs

sunset:
    data:
        nao:
            pref: 13

wbgt:
    panel:
        offset_x: 1340
        offset_y: 0
        width: 860
        height: 300

    data:
        env_go:
            url: https://www.wbgt.env.go.jp/graph_ref_td.php?region=03&prefecture=44&point=44132
    icon:
        face:
            - path: img/face_1.png
              brightness: 1.5
            - path: img/face_2.png
              brightness: 1.5
            - path: img/face_3.png
              brightness: 1.5
            - path: img/face_4.png
              brightness: 1.5
            - path: img/face_5.png
              brightness: 1.5

font:
    path: font
    map:
        jp_regular: migmix-1p-regular.ttf
        jp_medium: migmix-1p-regular.ttf
        jp_bold: migmix-1p-bold.ttf

        en_cond_bold: Antonio-Bold.ttf
        en_cond: Antonio-Regular.ttf

        en_medium: migmix-1p-regular.ttf
        en_bold: migmix-1p-bold.ttf

        # jp_regular: A-OTF-UDShinGoPr6N-Regular.otf
        # jp_medium: A-OTF-UDShinGoPr6N-Medium.otf
        # jp_bold: A-OTF-UDShinGoPr6N-Bold.otf

        # en_cond_bold: FuturaStd-CondensedBold.otf
        # en_cond: FuturaStd-Condensed.otf

        # en_medium: FrutigerNeueLTW1G-Medium.otf
        # en_bold: FrutigerNeueLTW1G-Bold.otf

webapp:
    timezone:
        offset: '+9'
        name: JST
        zone: Asia/Tokyo

    static_dir_path: react/dist
# slack:
#   from: E-Ink Weather Panel

#   bot_token: xoxb-XXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX

#   error:
#     channel:
#       name: "#error"
#       id: xxxxxxxxxxx
#     interval_min: 180
