PANEL:
  SERVER:
    IP: 192.168.0.10
    API_KEY: e7b98bfjdfldkfkd
    API_SECRET: gfklgjdgskjfsgfdgsdhfgfgsfdgfsgsdffdsgfgsdg
  DEVICE:
    UUID: 10003300-0007-0030-0003-000000000000
    WIDTH: 1600
    HEIGHT: 1200

INFLUXDB:
  ADDR: 192.168.0.10
  PORT: 8086
  DB: sensor

WEATHER:
  WIDTH: 1600
  HEIGHT: 300
  DATA:
    YAHOO:
      URL: https://weather.yahoo.co.jp/weather/jp/13/4410.html

POWER:
  WIDTH: 1600
  HEIGHT: 300
  OVERLAP: 100
  DATA:
    TYPE: raspberrypi
    HOST: rasp-meter-5
    PARAM:
      NAME: power
      FORMAT: '{:.0f}'
      UNIT: W
      RANGE:
        - 0
        - 3000

SENSOR:
  WIDTH: 1600
  HEIGHT: 700
  ROOM_LIST:
    - LABEL: 
      HOST: 屋外
        - NAME: ESP32-outdoor-1
          TYPE: esp32
        - NAME: rasp-meter-8
          TYPE: raspberrypi
      ICON: off
    - LABEL: リビング
      HOST:
        - NAME: rasp-meter-1
          TYPE: raspberrypi
      ICON: on
    - LABEL: 和室
      TYPE: raspberrypi
      HOST:
        - NAME: rasp-meter-2
          TYPE: raspberrypi
      ICON: on
    - LABEL: 洋室A
      HOST:
        - NAME: NONE
          TYPE: raspberrypi
      ICON: on
    - LABEL: 洋室B
      HOST:
        - NAME: rpi-cm4-sensor-1
          TYPE: raspberrypi
      ICON: on
    - LABEL: 洋室C
      HOST:
        - NAME: rpi-cm4-sensor-2
          TYPE: raspberrypi
      ICON: on
    - LABEL: 家事室
      HOST:
        - NAME: rasp-meter-4
          TYPE: raspberrypi
      ICON: on
    - LABEL: 書斎
      HOST:
        - NAME: rasp-meter-3
          TYPE: raspberrypi
      ICON: on

  PARAM_LIST:
    - NAME: temp
      FORMAT: '{:.1f}'
      UNIT: C
      RANGE: auto
      SIZE_SMALL: False
    - NAME: humi
      FORMAT: '{:.1f}'
      UNIT: '%'
      RANGE: auto
      SIZE_SMALL: False
    - NAME: co2
      FORMAT: '{:.0f}'
      UNIT: ppm
      RANGE: auto
      SIZE_SMALL: True
    - NAME: lux
      FORMAT: '{:.0f}'
      UNIT: lux
      RANGE:
        - 1
        - 3000
      SCALE: log
      SIZE_SMALL: True
  ICON:
    LIGHT:
      'ON': ../img/light-on.png
      'OFF': ../img/light-off.png

FONT:
  PATH: ../font/ # スクリプトのフォルダからの相対パス
  MAP:
    JP_REGULAR: A-OTF-ShinGoPro-Regular.otf
    JP_MEDIUM: A-OTF-ShinGoPro-Medium.otf
    JP_BOLD: A-OTF-ShinGoPro-Bold.otf
    EN_COND_BOLD: FuturaStd-CondensedBold.otf
    EN_COND: FuturaStd-Condensed.otf
    EN_MEDIUM: FuturaStd-Medium.otf
    EN_BOLD: FuturaStd-Bold.otf
