LIVENESS:
  FILE: /dev/shm/healthz

PANEL:
  SERVER:
    IP: 192.168.0.10
    API_KEY: e7b98bfjdfldkfkd
    API_SECRET: gfklgjdgskjfsgfdgsdhfgfgsfdgfsgsdffdsgfgsdg
  DEVICE:
    UUID: 10003300-0007-0030-0003-000000000000
    WIDTH: 3200
    HEIGHT: 1800
  UPDATE:
    INTERVAL: 120

INFLUXDB:
  URL: http://proxy.green-rabbit.net:8086
  TOKEN: fffjkjkgfklhjglkjiojtroijojhkljhklghklfjklhhlnklhnklfgnhklgnhgfdlhfgnhlkngdfnfnhgdkfnh==
  ORG: home
  BUCKET: sensor

WALL:
  IMAGE:
    - PATH: ../img/mascot.png
      BRIGHTNESS: 2
      OFFSET_X: 1550
      OFFSET_Y: 580

TIME:
  PANEL:
    MARGIN_X: 20
    MARGIN_Y: 20
    
WEATHER:
  PANEL:
    WIDTH: 3200
    HEIGHT: 1000
  DATA:
    YAHOO:
      URL: https://weather.yahoo.co.jp/weather/jp/13/4410/13113.html
  ICON:
    ARROW:
      PATH: ../img/arrow.png
    THERMO:
      PATH: ../img/thermo.png
      BRIGHTNESS: 1.2
    CLOTHES:
      PATH: ../img/clothes.png
      BRIGHTNESS: 1.2
    PRECIP:
      PATH: ../img/precip.png
      BRIGHTNESS: 1.3
    WIND:
      PATH: ../img/wind.png
      BRIGHTNESS: 1.3
      
POWER:
  PANEL:
    WIDTH: 1600
    HEIGHT: 510
    OVERLAP: 380
  DATA:
    HOST:
      NAME: rasp-meter-5
      TYPE: rasp
    PARAM:
      NAME: power
      FORMAT: '{:,.0f}'
      UNIT: W
      RANGE:
        - 0
        - 5000

SENSOR:
  PANEL:
    WIDTH: 1600
    HEIGHT: 690
    OVERLAP: 10
  ROOM_LIST:
    - LABEL: 屋外
      HOST:
        - NAME: ESP32-outdoor-1
          TYPE: esp32
        - NAME: rasp-meter-8
          TYPE: rasp
      ICON: off
    - LABEL: リビング
      HOST:
        - NAME: rpi-cm4-sensor-6
          TYPE: rasp
      ICON: on
    - LABEL: 和室
      TYPE: rasp
      HOST:
        - NAME: rasp-meter-2
          TYPE: rasp
      ICON: on
    - LABEL: 洋室A
      HOST:
        - NAME: rpi-cm4-sensor-1
          TYPE: rasp
      ICON: on
    - LABEL: 洋室B
      HOST:
        - NAME: rpi-cm4-sensor-2
          TYPE: rasp
      ICON: on
    - LABEL: 洋室C
      HOST:
        - NAME: rpi-cm4-sensor-3
          TYPE: rasp
      ICON: on
    - LABEL: 家事室
      HOST:
        - NAME: rpi-cm4-sensor-4
          TYPE: rasp
      ICON: on
    - LABEL: 書斎
      HOST:
        - NAME: rasp-meter-3
          TYPE: rasp
      ICON: on
  PARAM_LIST:
    - NAME: temp
      FORMAT: '{:.1f}'
      UNIT: '℃'
      RANGE: auto
      SCALE: linear
      SIZE_SMALL: False
    - NAME: humi
      FORMAT: '{:.1f}'
      UNIT: '%'
      RANGE: auto
      SCALE: linear
      SIZE_SMALL: False
    - NAME: co2
      FORMAT: '{:,.0f}'
      UNIT: ppm
      RANGE: auto
      SCALE: linear
      SIZE_SMALL: True
    - NAME: lux
      FORMAT: '{:,.0f}'
      UNIT: LUX
      RANGE:
        - 1
        - 40000
      SCALE: log
      SIZE_SMALL: True
  ICON:
    LIGHT:
      # NOTE: ON/OFF は「'」で囲わないと文字列以外に変換されてしまうので注意
      'ON':
        PATH: ../img/light-on.png
      'OFF':
        PATH: ../img/light-off.png

RAIN_CLOUD:
  PANEL:
    OFFSET_X: 1650
    OFFSET_Y: 900
    WIDTH: 1550
    HEIGHT: 910
  LEGEND:
    BAR_SIZE: 50
    OFFSET_X: 290
    OFFSET_Y: 870
  DATA:
    JMA:
      URL: https://www.jma.go.jp/bosai/nowc/#zoom:12/lat:35.682677/lon:139.762230/colordepth:deep/elements:hrpns&slmcs
      
FONT:
  PATH: ../font/ # スクリプトのフォルダからの相対パス
  MAP:
    JP_REGULAR: A-OTF-UDShinGoPr6N-Regular.otf
    JP_MEDIUM: A-OTF-UDShinGoPr6N-Medium.otf
    JP_BOLD: A-OTF-UDShinGoPr6N-Bold.otf

    EN_COND_BOLD: FuturaStd-CondensedBold.otf
    EN_COND: FuturaStd-Condensed.otf
    
    EN_MEDIUM: FuturaStd-Medium.otf
    EN_BOLD: FrutigerNeueLTW1G-Bold.otf

