PANEL:
  SERVER:
    IP: 192.168.0.10
    API_KEY: e7b98bfjdfldkfkd
    API_SECRET: gfklgjdgskjfsgfdgsdhfgfgsfdgfsgsdffdsgfgsdg
  DEVICE:
    UUID: 10003300-0007-0030-0003-000000000000
    WIDTH: 1600
    HEIGHT: 1200

INFLUXDB:
  ADDR: 192.168.0.10
  PORT: 8086
  DB: sensor

WEATHER:
  WIDTH: 1600
  HEIGHT: 300
  DATA:
    YAHOO:
      URL: https://weather.yahoo.co.jp/weather/jp/13/4410.html

POWER:
  WIDTH: 1600
  HEIGHT: 300
  OVERLAP: 100
  DATA:
    TYPE: raspberrypi
    HOST: rasp-meter-5
    PARAM:
      NAME: power
      FORMAT: '{:.0f}'
      UNIT: W
      RANGE:
        - 0
        - 3000

SENSOR:
  WIDTH: 1600
  HEIGHT: 700
  ROOM_LIST:
    - LABEL: 屋外
      TYPE: esp32
      HOST: ESP32-outdoor-1
    - LABEL: リビング
      TYPE: raspberrypi
      HOST: rasp-meter-1
    - LABEL: 和室
      TYPE: raspberrypi
      HOST: rasp-meter-2
    - LABEL: 洋室A
      TYPE: raspberrypi
      HOST: NONE
    - LABEL: 洋室B
      TYPE: raspberrypi
      HOST: NONE
    - LABEL: 洋室C
      TYPE: raspberrypi
      HOST: NONE
    - LABEL: 家事室
      TYPE: raspberrypi
      HOST: rasp-meter-4
    - LABEL: 書斎
      TYPE: raspberrypi
      HOST: rasp-meter-3
  PARAM_LIST:
    - NAME: temp
      FORMAT: '{:.1f}'
      UNIT: C
      RANGE:
        - 10
        - 40
      SIZE_SMALL: False
    - NAME: humi
      FORMAT: '{:.1f}'
      UNIT: '%'
      RANGE:
        - 0
        - 100
      SIZE_SMALL: False
    - NAME: co2
      FORMAT: '{:.0f}'
      UNIT: ppm
      RANGE:
        - 0
        - 1400
      SIZE_SMALL: True
    - NAME: lux
      FORMAT: '{:.0f}'
      UNIT: lux
      RANGE:
        - 1
        - 3000
      SCALE: log
      SIZE_SMALL: True
  ICON:
    LIGHT:
      'ON': ../img/light-on.png
      'OFF': ../img/light-off.png

FONT:
  PATH: ../font/ # スクリプトのフォルダからの相対パス
  MAP:
    JP_REGULAR: A-OTF-ShinGoPro-Regular.otf
    JP_MEDIUM: A-OTF-ShinGoPro-Medium.otf
    JP_BOLD: A-OTF-ShinGoPro-Bold.otf
    EN_COND_BOLD: FuturaStd-CondensedBold.otf
    EN_COND: FuturaStd-Condensed.otf
    EN_MEDIUM: FuturaStd-Medium.otf
    EN_BOLD: FuturaStd-Bold.otf
